spring:
  profiles:
    active: DEV
  liquibase:
    enabled: true
    change-log: classpath:liquibase/liquibase-changeLog.xml
  cache:
    ehcache:
      config: classpath:ehcache.xml

default:
   locale: en
   async:
      corePoolSize: 4
      maxPoolSize: 100
      queueCapacity: 5000

logging:
   level:
      org:
         springframework: WARN
         hibernate: WARN

