default:
   locale: en
   async:
      corePoolSize: 4
      maxPoolSize: 100
      queueCapacity: 5000

logging:
   level:
      org:
         springframework: WARN
         hibernate: WARN

liquibase:
    change-log: classpath:liquibase-changeLog.xml